app:
  port: 8000
db:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  name: "stomp-db"
  ssl: false
email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  auth_token: "my-secret-token"
