name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Toolchain info
      run: |
        cargo --version --verbose
        rustc --version
        argo clippy --version

    - name: Lint
      run: |
        cargo fmt -- --check
        cargo clippy -- -D warnings

    - name: Test
      run: |
        cargo check
        cargo test --all
          
    - name: Coverage
      run: |
        cargo install tarpaulin
        cargo tarpaulin --ignore-tests
